# Generated by Django 3.1.1 on 2020-09-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tingerprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tingerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
